### ISSUE TITLE
Error validating curator metadata template

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwas-deposition-app#3]
With the second uploading attempt, I got an error text but the error is WRONG -” Submission status: INVALID Error: Studies: Column 'Study Accession' in row(s) [1] lacks mandatory value”. I was submitting the “curator” template, where no “Study Accession’ column is present. The ‘Study Accession’ column is only present in the SS template. AB

**Comment by tudorgroza** [comment]
@jstewart-ebi - please provide the file for testing, otherwise, it's practically impossible to reproduce the error and fix.

**Comment by tudorgroza** [comment]
Assumed to be fixed.
